### ISSUE TITLE
JsonFormatterのkeysにdictを渡した場合出力のkeyをリネームできる

### ISSUE THREAD

**Issue by agarichan** [agarichan/aglog#1]
```yaml
formatters:
  json:
    (): aglog.JsonFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S"
    indent: 2
    colorize: true
    keys:
      astime: datetime
      message: msg
```

こんな感じ？
