### ISSUE TITLE
JsonFormatterのkeysで指定したものがnullの場合keyを表示しないオプションを追加

### ISSUE THREAD

**Issue by agarichan** [agarichan/aglog#2]
文字列+?をつけるとnullの場合keyを表示しないようにするとか。

```yaml
  json:
    (): aglog.JsonFormatter
    keys:
      - message
      - exc_info?
      - stack_info?
 ```
